events {}

http {
  include mime.types;
  server {
    listen 80;

    location / {
      root /usr/share/nginx/html;
      try_files $uri /index.html;
    }

    location /auth/ {
      proxy_pass http://api:8080;
    }

    location /tasks {
      proxy_pass http://api:8080;
    }
  }
}
